import Image from "next/image";
import Link from "next/link";
import { CalendarDays, CheckCircle2, FilePlus2, Gift, Headphones, History, LockKeyhole, RefreshCcw, ShieldCheck } from "lucide-react";
import { Header } from "@/components/header";
import { SiteFooter } from "@/components/site-footer";

const tiers = [["1–3 days early", "+2%"], ["4–7 days early", "+5%"], ["8–14 days early", "+10%"], ["15+ days early", "+15%"]];

export default function HowItWorksPage() {
  return <main className="how-page bg-white text-[#07142d]">
    <Header active="how" />
    <section className="overflow-hidden border-t border-[#edf1ef] bg-linear-to-br from-white via-white to-[#f4faf7]"><div className="mx-auto grid min-h-[370px] max-w-[1120px] items-center px-7 pt-8 lg:grid-cols-[52%_48%]">
      <div className="z-10 py-10"><h1 className="text-[44px] font-bold leading-[1.06] tracking-[-.05em] sm:text-[54px]">How Vuior works</h1><p className="mt-4 text-[17px] leading-7 text-[#596885]">Add your bills, pay early, and earn credits.<br/>The earlier you pay, the more you save.</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/signup" className="flex h-12 items-center rounded-md bg-[#008f64] px-7 text-[12px] font-semibold text-white">Create free account</Link><a href="#rewards" className="flex h-12 items-center rounded-md border border-[#009b6b] px-7 text-[12px] font-semibold text-[#008f64]">See rewards</a></div><div className="mt-8 flex flex-wrap gap-7 text-[10px] font-semibold"><span className="flex items-center gap-2"><LockKeyhole size={18} className="text-[#00a36a]"/>Pay securely</span><span className="flex items-center gap-2"><CheckCircle2 size={18} className="text-[#00a36a]"/>No hidden fees</span><span className="flex items-center gap-2"><RefreshCcw size={18} className="text-[#00a36a]"/>Cancel anytime</span></div></div>
      <div className="relative hidden h-[360px] lg:block"><Image src="/how-it-works.png" alt="Vuior app showing early bill payments and earned credits" fill sizes="(min-width: 1024px) 48vw, 100vw" className="object-contain object-center" priority/></div>
    </div></section>

    <section className="mx-auto max-w-[960px] px-6 py-10"><h2 className="text-center text-[22px] font-bold">Three simple steps</h2><div className="mt-7 grid gap-10 md:grid-cols-3">{[["01", FilePlus2, "Add your bills", "Connect or enter your recurring bills in just a few taps."], ["02", CalendarDays, "Pay before the due date", "Choose when to pay or set autopay. The earlier you pay, the more you earn."], ["03", Gift, "Earn credits", "Get rewarded with credits based on how early you pay eligible bills."]].map(([number, Icon, title, text], i) => {const I=Icon as typeof Gift; return <article key={String(title)} className="relative min-h-[205px] rounded-xl border border-[#dfe7e4] bg-white p-5 shadow-[0_6px_20px_rgba(25,55,47,.025)]"><div className="flex items-center gap-5"><strong className="text-[28px] text-[#83dcbc]">{String(number)}</strong><I size={27} className="text-[#00a36a]"/></div><h3 className="mt-4 text-[13px] font-bold">{String(title)}</h3><p className="mt-3 max-w-[195px] text-[10px] leading-5 text-[#596885]">{String(text)}</p>{i < 2 && <span className="absolute -right-7 top-1/2 hidden text-[#aebbb7] md:block">⇢</span>}</article>})}</div></section>

    <section id="rewards" className="bg-linear-to-r from-[#004a3e] to-[#003c34] text-white"><div className="mx-auto grid max-w-[1000px] gap-5 px-7 py-7 md:grid-cols-[210px_repeat(4,1fr)]"><div><h2 className="text-[20px] font-bold leading-6">The earlier you pay,<br/>the more you earn</h2><p className="mt-3 text-[10px] leading-4 text-[#c7ded7]">Earn credits on eligible bills when you pay early.</p></div>{tiers.map(([days, reward]) => <div key={days} className="rounded-lg border border-[#ffffff24] bg-[#005647] p-4 text-center"><b className="text-[10px]">{days}</b><strong className="mt-4 block text-[27px]">{reward}</strong><small className="text-[9px]">in credits</small></div>)}</div></section>

    <section className="mx-auto max-w-[820px] px-6 py-8"><h2 className="text-center text-[20px] font-bold">What you can do with Vuior</h2><div className="mt-5 space-y-2">{[[CalendarDays, "Track upcoming bills and due dates", "See what’s coming up, so you never miss a due date."], [RefreshCcw, "Pay bills and manage autopay", "Pay instantly or set autopay for peace of mind."], [History, "View credits, savings, and history", "See your credits, total savings, and transactions in one place."]].map(([Icon,title,text], index) => {const I=Icon as typeof History; return <article key={String(title)} className={`grid min-h-[74px] items-center overflow-hidden rounded-lg border border-[#e2e9e6] ${index % 2 ? "md:grid-cols-[1fr_1fr]" : "md:grid-cols-[1fr_1fr]"}`}><div className={`${index % 2 ? "md:order-2" : ""} flex h-full items-center justify-center bg-[#f5faf8]`}><I className="text-[#00a36a]" size={25}/></div><div className="border-l-2 border-[#00a36a] px-5 py-3"><b className="text-[10px]">{String(title)}</b><p className="mt-1 text-[9px] leading-4 text-[#596885]">{String(text)}</p></div></article>})}</div></section>

    <section className="mx-auto grid max-w-[960px] gap-6 px-7 pb-7 sm:grid-cols-2 lg:grid-cols-4">{[[LockKeyhole,"Secure payments","Bank-grade security keeps your payments and data safe."], [History,"Clear payment history","View all transactions, credits, and receipts anytime."], [ShieldCheck,"Protected account","Advanced controls help protect your account."], [Headphones,"Support when you need it","Real humans are ready to help every step of the way."]].map(([Icon,title,text]) => {const I=Icon as typeof ShieldCheck; return <div key={String(title)} className="flex gap-3"><I size={25} className="shrink-0 text-[#00a36a]"/><span><b className="text-[10px]">{String(title)}</b><p className="mt-1 text-[8px] leading-4 text-[#596885]">{String(text)}</p></span></div>})}</section>

    <section className="mx-auto mb-7 grid max-w-[800px] items-center gap-5 rounded-xl bg-linear-to-r from-[#004a3e] to-[#002f29] px-8 py-6 text-white sm:grid-cols-[1fr_auto]"><div><h2 className="text-[21px] font-bold leading-6">Start getting more from<br/>the bills you already pay</h2><p className="mt-2 text-[10px] text-[#c7ded7]">Join Vuior today and earn credits every time you pay early.</p></div><div className="flex gap-3"><Link className="flex h-10 items-center rounded-md bg-[#00a36a] px-6 text-[10px] font-semibold" href="/signup">Create free account</Link><Link className="flex h-10 items-center rounded-md border border-[#9dc6b9] px-6 text-[10px] font-semibold" href="/login">Log in</Link></div></section>
    <SiteFooter />
  </main>;
}
